Enable sys container writes to /proc/sys/kernel/shm*
Even though the /proc/sys/kernel/shm* files (to control shared memory limits) are
namespaced in the kernel via the IPC namespace, the kernel only allows true root
to write to these files. Therefore, a sysbox container root user is not allowed
to write to these files. For example:

$ docker run --runtime=sysbox-runc --rm -it alpine sh -c "echo 1024 > /proc/sys/kernel/shmmax"
error: permission denied.

To overcome this, improve the sysbox-fs procSysKernel handler to service
accesses to these files without entering the Sysbox container's user-namespace.
This also required corresponding changes to the passthrough handler.

Signed-off-by: Cesar Talledo <cesar.talledo@docker.com>